CC = gcc


all: 1.c 2.c 3.c 4.c
	$(CC) -o program1 1.c
	$(CC) -o program2 2.c
	$(CC) -o program3 3.c
	$(CC) -o program4 4.c


clean: program1.exe program2.exe program3.exe program4.exe
	rm program1.exe program2.exe program3.exe program4.exe